sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt58base

before_script:
  - export PATH=$PATH:/opt/qt58/bin

script:
  - /opt/qt58/bin/qmake
  - make
